resolver: nightly-2018-05-10
packages:
- .
extra-deps:
  - containers-0.5.11.0
  - ghcjs-dom-0.9.4.0
  - ghcjs-dom-jsaddle-0.9.4.0
  - jsaddle-dom-0.9.3.1
  - jsaddle-0.9.6.0
  - ref-tf-0.4.0.1
  - jsaddle-warp-0.9.6.0
